name: Tests of vote processing rules

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ruild container and run tests
      run:  docker build --tag test -f voting_systems/tests/Dockerfile .
